version: '3.8'

services:
  polyp-detection-yolov7:
    build:
      context: .
      dockerfile: Dockerfile
    image: polyp-detection-yolov7:latest
    container_name: polyp-detection-yolov7
    volumes:
      - ./models:/workspace/models
      - ./utils:/workspace/utils
      - ./inference:/workspace/inference
      - ./scripts:/workspace/scripts
      - ./requirements.txt:/workspace/requirements.txt
    stdin_open: true
    tty: true
